feat: added goose migrations and updated readme

diff --git a/api/Makefile b/api/Makefile
--- a/api/Makefile
+++ b/api/Makefile
@@ -1,6 +1,28 @@
-.PHONY: up down build logs restart clean swag-init
+-include .env
+export
+
+.PHONY: migrate-create up down build logs restart clean swag-init
+
 
 DOCKER_COMPOSE=docker compose --env-file .env -f docker/docker-compose.yaml
+
+# Usage: make migrate-create name=create_users_table
+migrate-create:
+	@if [ -z "$(name)" ]; then \
+		echo "❌ Missing migration name. Usage: make migrate-create name=your_migration_name"; \
+		exit 1; \
+	fi
+	goose -dir internal/database/migrations create $(name) sql
+
+# DB URL build từ .env
+DB_URL=postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=$(POSTGRES_SSLMODE)
+
+# Run migrations
+migrate-up:
+	goose -dir internal/database/migrations postgres "$(DB_URL)" up
+
+migrate-down:
+	goose -dir internal/database/migrations postgres "$(DB_URL)" down
 
 # Start containers
 up:
